### ISSUE TITLE
Support ALAC in Chromecast

### ISSUE THREAD

**Issue by adelatour11** [Hedda/Plex-DNLA-client-profiles#2]
Hello

i have a big itunes library full of Apple Lossless (ALAC) files. I'm searching for a way to play it on my chromecast without transcoding to mp3.

ALAC is not supported by chromecast but FLAC is. I am searching for a way to transcode my files from .m4A ALAC codec to FLAC to make playable in my chromecast.

**Comment by Hedda** [comment]
@adelatour11, this is unofficial repository of DNLA profiles for Plex Media Server.

You need to address all your support questions to upstream => https://plex.tv

If Plex Media Server supports transcoding to FLAC then maybe they can add it.
